jay/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns  # For using static files
from django.conf.urls.static import static  # For using static files
from django.conf import settings  # For using media files
from music import views as music_views  # For importing music views to use as index
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', music_views.index, name='home'),  # To remove in the future
    path('accounts/', include('accounts.urls')),
    path('music/', include('music.urls')),

    # Password reset Urls
    path('', include('django.contrib.auth.urls')),

    # url for redirecting to the appropriate oath application which the social websites provides
    path('oauth/', include('social_django.urls', namespace='social')),
]

# static files
urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.urls import path, re_path
from . import views

app_name = 'music'

urlpatterns = [
    # URL patterns for album list and album details
    path('', views.index, name='index'),  # Album list
    path('<int:album_id>/', views.album_detail, name='album_detail'),

    # URL patterns for song list and song details
    path('songs/', views.song_list, name='song_list'),
    re_path('(?P<id>[0-9])/(?P<slug>[\w-]+)/', views.song_detail, name='song_detail'),

    # URL pattern for liking a song
    path('like/', views.like_song, name='like_song'),

    # URL pattern for search bar
    path('search/', views.search, name='search'),
]

music/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# Create your models here.

# Album Model
class Album(models.Model):
    artist = models.CharField(max_length=200)
    album_title = models.CharField(max_length=250)
    album_logo = models.ImageField(default='default.png', blank=True)

    def __str__(self):
        return self.album_title + ' - ' + self.artist

    def get_absolute_url(self):
        return reverse('music:album_detail', args=[self.id])


# Song Model
class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE, blank=True, null=True)
    artist = models.CharField(max_length=200)
    song_title = models.CharField(max_length=250)
    slug = models.SlugField()
    cover_photo = models.ImageField(default='default.png', blank=True)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.song_title

    def total_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse('music:song_detail', args=[self.id, self.slug])


# Song Comments Model
class SongComment(models.Model):
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(max_length=500)
    reply = models.ForeignKey('SongComment', null=True, related_name='replies', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.song.song_title + ' - ' + self.user.username

music/forms.py
from django import forms
from .models import Song, SongComment


class SongCommentForm(forms.ModelForm):
    content = forms.CharField(
        label="",
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'Please login to drop a comment',
                'rows': '4',
                'cols': '50'
            }
        )
    )

    class Meta:
        model = SongComment
        fields = ('content',)

music/views.py
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from .models import Album, Song, SongComment
from .forms import SongCommentForm
from django.db.models import Q


# Create your views here.

# View function for album list and album details
def index(request):
    albums = Album.objects.all()
    query = request.GET.get('q')
    if query:
        albums = Album.objects.filter(
            Q(artist__icontains=query) |
            Q(album_title__icontains=query)
        )
    return render(request, 'music/index.html', {'albums': albums})


def album_detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)  # album = Album.objects.get(pk=album_id)
    return render(request, 'music/album_detail.html', {'album': album})


# View functions for song list and song detail
def song_list(request):
    song_list = Song.objects.all().order_by('artist')
    latest_songs = Song.objects.all()[:5:2]
    context = {
        'song_list': song_list,
        'latest_songs': latest_songs,
    }
    return render(request, 'music/song_list.html', context)


def song_detail(request, id, slug):
    song = get_object_or_404(Song, id=id, slug=slug)  # song = Song.objects.get(slug=slug)
    comments = SongComment.objects.filter(song=song, reply=None).order_by('-id')
    is_liked = False
    if song.likes.filter(id=request.user.id).exists():
        is_liked = True

    if request.method == 'POST':
        comment_form = SongCommentForm(request.POST or None)
        if comment_form.is_valid():
            content = request.POST.get('content')
            reply_id = request.POST.get('comment_id')
            comment_qs = None
            if reply_id:
                comment_qs = SongComment.objects.get(id=reply_id)
            comment = SongComment.objects.create(song=song, user=request.user, content=content, reply=comment_qs)
            comment.save()
            # return HttpResponseRedirect(song.get_absolute_url())
    else:
        comment_form = SongCommentForm()

    context = {
        'song': song,
        'is_liked': is_liked,
        'total_likes': song.total_likes(),
        'comments': comments,
        'comment_form': comment_form,

    }
    if request.is_ajax():
        html = render_to_string('music/song_comments.html', context, request=request)
        return JsonResponse({'form': html})

    return render(request, 'music/song_detail.html', context)


# View function for liking a particular song
def like_song(request):
    # song = get_object_or_404(Song, id=request.POST.get('song_id'))
    song = get_object_or_404(Song, id=request.POST.get('id'))
    is_liked = False
    if song.likes.filter(id=request.user.id).exists():
        song.likes.remove(request.user)
        is_liked = False
    else:
        song.likes.add(request.user)
        is_liked = True
    context = {
        'song': song,
        'is_liked': is_liked,
        'total_likes': song.total_likes,
    }
    if request.is_ajax():
        html = render_to_string('music/song_like_section.html', context, request=request)
        return JsonResponse({'form': html})


def search(request):
    albums = Album.objects.all()
    songs = Song.objects.all()
    query = request.GET.get('q')
    if query:
        albums = Album.objects.filter(
            Q(artist__icontains=query) |
            Q(album_title__icontains=query)
        )
    if query:
        songs = Song.objects.filter(
            Q(artist__icontains=query) |
            Q(song_title__icontains=query)
        )
    context = {
        'albums': albums,
        'songs': songs
    }
    return render(request, 'music/search.html', context)

music/templates/music/album_detail.html
{% extends 'base_template.html' %}

{% block content %}

<div id="navbar-section">
    {% include 'navbar.html' %}
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-5">
            <h3> List of all songs in an album</h3>
            <img src="{{album.album_logo.url}}" class="img-fluid" style="height:300px; width:100%;">
        </div>
        <div class="col-sm-7" style="padding-top:90px">
            <p style="font-size:25px">{{album.artist}}</p>
            <h1>{{album.album_title}}</h1>
        </div>
    </div>

    <hr>
    <div class="song-list">
        <ul>
        {% for songs in album.song_set.all %}
            <a href="{% url 'music:song_detail' songs.id songs.slug %}">
                <li><img src="{{album.album_logo.url}}" class="img-fluid"> {{songs.song_title}}</li>
            </a>
        {% endfor %}
        </ul>
    </div>




</div>

{% endblock %}

music/templates/music/index.html
{% extends 'base_template.html' %}

{% block content %}
<div class="banner">

</div>

<div id="navbar-section">
    {% include 'navbar.html' %}
</div>
<h3>This is the Index page that shows all Albums</h3>

<div class="container">
    <div class="row">
        {% for album in albums %}
        <div class="col-md-3" id="album-list">
            <a href="{{ album.get_absolute_url }}">
                <img src="{{album.album_logo.url}}" class="img-fluid" style="height:225px; width:255px;">
                <p>{{album.artist}}</p>
                <h6>{{album.album_title}}</h6>
                <small>Total songs: {{album.song_set.count}}</small>
            </a>
        </div>
        {% endfor %}
    </div>
</div>



{% endblock %}

music/templates/music/search.html
{% extends 'base_template.html' %}

{% block content %}

<div id="navbar-section">
    {% include 'navbar.html' %}
</div>
<h3>This is the Search page that shows all contents</h3>

<div class="container">
    <h4 style="padding-top:30px">All Albums</h4>
    <div class="row">
        {% for album in albums %}
        <div class="col-md-3" id="album-list">
            <a href="{{ album.get_absolute_url }}">
                <img src="{{album.album_logo.url}}" class="img-fluid" style="height:225px; width:255px;">
                <p>{{album.artist}}</p>
                <h6>{{album.album_title}}</h6>
                <small>Total songs: {{album.song_set.count}}</small>
            </a>
        </div>
        {% empty %}
        <div class="container">
            <h4>No album having search term "{{request.GET.q}}"</h4>
        </div>


        {% endfor %}
    </div>

    <h4 style="padding-top:30px">All songs</h4>
     <div class="row">

        {% for song in songs %}
            <div class="col-md-3">
                <a href="{% url 'music:song_detail' song.id song.slug %}">
                    <img src="{{song.cover_photo.url}}" class="img-fluid" style="height:225px; width:255px;"> {{song.artist}} - {{song.song_title}}
                </a>
            </div>
            {% empty %}
            <div class="container">
                <h4>No song having search term "{{request.GET.q}}"</h4>
            </div>

        {% endfor %}
     </div>


</div>


{% endblock %}

music/templates/music/song_comments.html
<!-- Comment section begins here -->
    <h6>{{ comments.count }} Comment{{ comments|pluralize}}</h6>

    <form method="post" class=" comment-form mt-4" action=".">
        {% csrf_token %}
        {{ comment_form.as_p }}
        {% if request.user.is_authenticated %}
            <input type="submit" value="submit" class="btn btn-outline-success">
        {% else %}
            <input type="submit" value="submit" class="btn btn-outline-success" disabled>
        {% endif %}
    </form>

    <hr>

    <div id="main-comment-section">
        {% for comment in comments %}
        <blockquote class="blockquote">
            <p class="mb-0"><small>{{ comment.content }}</small></p>
            <footer class="blockquote-footer"> <small><cite title="by "> {{ comment.user|capfirst }} </cite></small>
                <button type="button" name="button" class="reply-btn btn btn-outline-dark btn-sm ml-2">Reply</button>
            </footer>
        </blockquote>

        <!-- Replies for comments --> <!--Should be inside the main comment section -->
        <div class="replied-comments container mt-2" style="display:none; padding-left:50px">

            {% for reply in comment.replies.all %}
            <blockquote class="blockquote">
                <p class="mb-0"><small>{{ reply.content }}</small></p>
                <footer class="blockquote-footer"> <small><cite title="by "> {{ reply.user|capfirst }} </cite></small> </footer>
            </blockquote>
            {% endfor %}

            <div class="form-group row">
                <form method="post" class="reply-form" action=".">
                    {% csrf_token %}
                    <input type="hidden" name="comment_id" value="{{ comment.id }}">
                    {{ comment_form.as_p }}
                    {% if request.user.is_authenticated %}
                        <input type="submit" value="submit" class="btn btn-outline-success">
                    {% else %}
                        <input type="submit" value="submit" class="btn btn-outline-success" disabled>
                    {% endif %}
                </form>
            </div>
        </div>

        {% endfor %}
    </div>

music/templates/music/song_detail.html
{% extends 'base_template.html' %}

{% block content %}

<!-- navbar included -->
<div id="navbar-section">
    {% include 'navbar.html' %}
</div>

<!-- Main content begins here -->
<div class="container">
    <div class="row">
        <div class="col-sm-5">
            <h3> Song Detail </h3>
            <img src="{{song.cover_photo.url}}" class="img-fluid" style="height:380px; width:100%;">
        </div>
        <div class="col-sm-7" style="padding-top:90px" id="song-info">
            <p style="font-size:25px">{{song.artist}}</p>
            <h1>{{song.song_title}}</h1>
            <br>
            <ul>
                <li><i class="fa fa-play"></i></li>

                <!-- Like -->
                <li>
                    <div id="song-like-section">
                        {% include 'music/song_like_section.html' %}
                    </div>
                </li>
                <!-- Like ends -->

                <li><a href="#comment-div" style="color:black"><i class="fa fa-comment-o"></i></a></li>
            </ul>
        </div>
    </div>

    <hr>
</div>

<div class="container" id="comment-div">
    {% include 'music/song_comments.html' %}
</div>


{% endblock %}

music/templates/music/song_like_section.html
{% if request.user.is_authenticated %}
<form action="{% url 'music:like_song' %}" method="post">
    {% csrf_token %}
    {% if is_liked %}
        <!--<i class="fa fa-heart" type="submit" name="song_id" value="{{song.id}}" style="color:red"></i>-->
        <button type="submit" id="song-like" name="song_id" value="{{song.id}}" class="fa fa-heart" style="color:red;"></button>
        <br> <small> {{total_likes}} like{{total_likes|pluralize}}</small>
    {% else %}
        <!--<i class="fa fa-heart-o" type="submit" name="song_id" value="{{song.id}}"></i>-->
        <button type="submit" id="song-like" name="song_id" value="{{song.id}}" class="fa fa-heart-o"></button>
        <br> <small> {{total_likes}} like{{total_likes|pluralize}}</small>
    {% endif %}
</form>
{% else %}
    <i class="fa fa-thumbs-up"></i>
    <br> <small style="font-size:14px"> {{total_likes}} like{{total_likes|pluralize}}</small>

{% endif %}

music/templates/music/song_list.html
{% extends 'base_template.html' %}

{% block content %}
<div class="banner" style="background-image: url(/static/images/bg3.jpg);">

</div>

<div id="navbar-section">
    {% include 'navbar.html' %}
</div>
<h3>This page shows a list of all the songs</h3>

<div class="container-fluid">
    <div class="row">

        <div class="col-sm-8">
            <div class="list-group list-group-flush" id="song-list">
            {% for song in song_list %}
                <a href="{% url 'music:song_detail' song.id song.slug %}" class="list-group-item list-group-item-action">
                    <img src="{{song.cover_photo.url}}" class="img-fluid"> {{song.artist}} - {{song.song_title}}
                </a>
            {% endfor %}
            </div>
        </div>

        <div class="col-sm-4">
            <h5> Latest Songs </h5>
            <hr>
            <div class="list-group list-group-flush" id="song-list">
                {% for latest in latest_songs %}
                    <a href="{% url 'music:song_detail' latest.id latest.slug %}" class="list-group-item list-group-item-action">
                        <img src="{{latest.cover_photo.url}}" class="img-fluid"> {{latest.artist}} - {{latest.song_title}}
                    </a>
                {% endfor %}
            </div>
        </div>

    </div>
</div>


{% endblock %}