accounts/urls.py
from django.urls import path
from .import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view'),
    path('signup/', views.signup_view, name='signup_view'),
]

jay/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns  # For using static files
from django.conf.urls.static import static  # For using static files
from django.conf import settings  # For using media files
from music import views as music_views  # For importing music views to use as index
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', music_views.index, name='home'),  # To remove in the future
    path('accounts/', include('accounts.urls')),
    path('music/', include('music.urls')),

    # Password reset Urls
    path('', include('django.contrib.auth.urls')),

    # url for redirecting to the appropriate oath application which the social websites provides
    path('oauth/', include('social_django.urls', namespace='social')),
]

# static files
urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.urls import path, re_path
from . import views

app_name = 'music'

urlpatterns = [
    # URL patterns for album list and album details
    path('', views.index, name='index'),  # Album list
    path('<int:album_id>/', views.album_detail, name='album_detail'),

    # URL patterns for song list and song details
    path('songs/', views.song_list, name='song_list'),
    re_path('(?P<id>[0-9])/(?P<slug>[\w-]+)/', views.song_detail, name='song_detail'),

    # URL pattern for liking a song
    path('like/', views.like_song, name='like_song'),

    # URL pattern for search bar
    path('search/', views.search, name='search'),
]

templates/base_template.html
{% load static %}


<!DOCTYPE html>
<html>
<head>
	<title>Home</title>

	<!-- Bootstrap core CSS -->
  	<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
  	<link href="/static/bootstrap/css/font-awesome.min.css" rel="stylesheet" type="text/css">

  	<link rel="stylesheet" type="text/css" href="/static/styles.css">
  	 <!-- jQuery (necessary for the use of jQuery) -->
    <script src="/static/bootstrap/js/jquery.min.js"></script>

	<script></script>
</head>
<body>

	<nav class="navbar navbar-expand-sm bg-dark navbar-dark sticky-top">
		 <!--brand logo-->
    	<a class="navbar-brand" href="{% url 'home' %}">Logo</a>

		<ul class="navbar-nav ml-auto">
			<li class="nav-item">
				<form class="form-inline" action="{% url 'music:search' %}">
					<input class="form-control" type="search" placeholder="Search" name="q" style="border-radius:0; background-color:#fff; color:grey; border:1px solid #fff">
					<button class="btn" type="submit" style="border-radius:0; background-color:#fff; color:grey; border:1px solid #fff">
						<i class="fa fa-search"></i>
					</button>
				</form>
			</li>
		</ul>
	</nav>

    {% block content %}

    {% endblock %}


	<script src="/static/bootstrap/js/bootstrap.min.js"></script>
	<!--<script type="text/javascript" src="/static/queryscript.js"></script>--> <!-- FOR EXTERNAL JAVASCRIPT -->

	<!-- This Ajax doesn't work on external script for some reasons -->
	<!-- Script for liking a song -->
	<script>
		//ajax and jquery script for like function
		$(document).ready(function(event){
			$(document).on('click', '#song-like', function(event){
				event.preventDefault();
				var pk = $(this).attr('value');
				$.ajax({
					type:'POST',
					url: '{% url "music:like_song" %}',
					data: {'id':pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
					dataType: 'json',
					success: function(response){
						$('#song-like-section').html(response['form'])
					},
					error: function(rs, e){
						console.log(rs.responseText);
					},
				});
			});
		});


		//script for comment reply toggle visible
        $(document).ready(function(e){
            $('.reply-btn').click(function(){
                $(this).parent().parent().next('.replied-comments').fadeToggle();
            });
        });


        //ajax script for comment function to prevent the whole page from loading
        $(document).ready(function(){
            $(document).on('submit', '.comment-form', function(event){
                event.preventDefault();
                console.log($(this).serialize());
                $.ajax({
                    type: 'POST',
                    url: $(this).attr('action'),
                    data: $(this).serialize(),
                    dataType: 'json',
                    success: function(response){
                        $('#comment-div').html(response['form']);
                        $('textarea').val('');
                        $('.reply-btn').click(function(){
                            $(this).parent().parent().next('.replied-comments').fadeToggle();
                            $('textarea').val('');
                        });
                    },
                    error: function(rs, e) {
                        console.log(rs.responseText);
                    },
                });
            });
        });


        //ajax script for comment replies function to prevent the whole page from loading
        $(document).ready(function(){
            $(document).on('submit', '.reply-form', function(event){
                event.preventDefault();
                console.log($(this).serialize());
                $.ajax({
                    type: 'POST',
                    url: $(this).attr('action'),
                    data: $(this).serialize(),
                    dataType: 'json',
                    success: function(response){
                        $('#comment-div').html(response['form']);
                        $('textarea').val('');
                        $('.reply-btn').click(function(){
                            $(this).parent().parent().next('.replied-comments').fadeToggle();
                            $('textarea').val('');
                        });
                    },
                    error: function(rs, e) {
                        console.log(rs.responseText);
                    },
                });
            });
        });

	</script>


</body>
</html>

templates/homepage.html
{% extends 'base_template.html' %}

{% block content %}
    <div id="navbar-section">
        {% include 'navbar.html' %}
    </div>
    <h3>This is the Homepage</h3>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-sm bg-light">
       <!-- Nav links-->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'music:index' %}"><i class="#"></i> Albums</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'music:song_list' %}"><i class="fa fa-music"></i> Songs</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#"><i class="fa fa-youtube-play"></i> Videos</a>
        </li>
    </ul>

    {% if user.is_authenticated %}
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <form action="{% url 'accounts:logout_view' %}" method="post">
                {% csrf_token %}
                <button type="submit" title="logout" class="btn">Logout</button>
            </form>
        </li>
    </ul>
    {% else %}
     <ul class="navbar-nav ml-auto">
        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login_view' %}">Sign in</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup_view' %}">Sign up</a></li>
    </ul>
    {% endif %}
</nav>